defaults:
  - diffusion: sd15
  - scorer: clip_flant5
  - algorithm: vqa_gradient
  - vanilla_sd: sd15
  - flux1: dev
  - logging: default
  - _self_

run:
  _target_: vlm_guidance.guidance.vqa_gradient.RunConfig
  negative_prompt: "blurry, low quality"
  height: 512
  width: 512
  num_inference_steps: 30
  guidance_scale: 7.5
  seed: 42
  batch_size: 1
  vqa_score: true
  vanilla_sd: false
  flux1: false

batch:
  prompts_file: ../datasets/subset.txt
  output_root_dir: subset
  skip_empty_lines: true
